version: '3.7'

networks:
  doko3000:
    name: doko3000

volumes:
  doko3000-couchdb-data:
  doko3000-couchdb-config:

services:
  doko3000:
    build: .
    image: doko3000
    container_name: doko3000
    restart: always
    networks:
      - doko3000
    env_file:
      - environment
  couchdb:
    image: couchdb
    container_name: doko3000-couchdb
    restart: always
    volumes:
      - doko3000-couchdb-data:/opt/couchdb/data
      - doko3000-couchdb-config:/opt/couchdb/etc/local.d
    networks:
      - doko3000
    env_file:
      - environment
  nginx:
    image: nginx:stable-alpine
    container_name: doko3000-nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/cert.pem
      - ./key.pem:/key.pem
    restart: always
    networks:
      - doko3000
