version: '3.7'

networks:
  doko3000:
    name: doko3000

volumes:
  couchdb-config:
  couchdb-data:
  certbot-config:
  certbot-www:

services:
  doko3000:
    build: .
    image: doko3000
    container_name: doko3000
    restart: always
    networks:
      - doko3000
  couchdb:
    image: couchdb
    container_name: doko3000-couchdb
    restart: always
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-config:/opt/couchdb/etc/local.d
    networks:
      - doko3000
  nginx:
    image: nginx:stable-alpine
    container_name: doko3000-nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./docker/nginx-https-letsencrypt.conf:/etc/nginx/conf.d/default.conf
      - ./doko3000/static:/usr/share/nginx/html/static
      - ./cards:/usr/share/nginx/html/static/img/cards
      - certbot-config:/etc/letsencrypt
      - certbot-www:/usr/share/nginx/html/certbot
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - doko3000
    command:
      "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: doko3000-certbot
    restart: always
    volumes:
      - certbot-config:/etc/letsencrypt
      - certbot-www:/usr/share/nginx/html/certbot
    networks:
      - doko3000
    entrypoint:
      "/bin/sh -c 'trap exit TERM; while :; do certbot --webroot-path=/usr/share/nginx/html/certbot renew; sleep 12h & wait $${!}; done;'"
