version: '3.7'

networks:
  doko3000:
    name: doko3000

volumes:
  doko3000-couchdb-config:
  doko3000-couchdb-data:

services:
  doko3000:
    build: ..
    image: doko3000
    container_name: doko3000
    restart: always
    networks:
      - doko3000
  couchdb:
    image: couchdb
    container_name: doko3000-couchdb
    restart: always
    volumes:
      - doko3000-couchdb-data:/opt/couchdb/data
      - doko3000-couchdb-config:/opt/couchdb/etc/local.d
    networks:
      - doko3000
  nginx:
    image: nginx:stable-alpine
    container_name: doko3000-nginx
    ports:
      - 80:80/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../doko3000/static:/usr/share/nginx/html/static
    restart: always
    networks:
      - doko3000
