name: add-release 2
on: [push]
  #push:
  #  tags: 'v*'

  upload-release:
    runs-on: ubuntu-latest
    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
